### PR TITLE
add greasemonkey script that prevents left/arrow keys from going to

### PR DESCRIPTION
**Pull request by kaizensoze**
next/prev article on nytimes

(btw: You can view as many nytimes articles as you want without a subscription in a private window in firefox, or in incognito mode in chrome.)

### CODE REVIEW

**Comment by sarahgerweck** [comment]
So this works great in Firefox, but I tried it in Chrome + Tampermonkey and it doesn't seem to work there. Any ideas or suggestions?

Chrome is actually where I would most like this to work, but I did specify Greasemonkey so I'll happily release the bounty either way. Thanks for picking this one up. :smile:

**Comment by kaizensoze** [comment]
Ah yeah it might need a few tweaks for Tampermonkey. I'll take a look.

**Comment by kaizensoze** [comment]
Ok so apparently tampermonkey is pretty terrible compared to greasemonkey. I added a separate file for the tampermonkey script (it has a dash in it and I commented in the files which is which). You're supposed to be able to just take the tampermonkey script file and drag onto the chrome extensions page but everytime I went to export the working script and then import it I got "Invalid header" so you'll need to go into the tampermonkey interface, add a script, copy the contents in and save. That should hopefully do the trick.

**Comment by sarahgerweck** [comment]
Seems to work perfectly! When I went to the "view raw" page in GitHub, Tampermonkey offered to install it for me, which seemed convenient enough. Thanks again for figuring this out (and going above & beyond the original ask to make it Chrome friendly).

**Comment by sarahgerweck** [comment]
This PR fixes #1.

**Comment by sarahgerweck** [comment]
Working great for me, go ahead & put in a claim on the bounty at your convenience and I'll approve it. (I think you have to initiate the payout.)
I doubled up the amount as a thank you for looping back to fix Chrome. :cocktail:

**Comment by kaizensoze** [comment]
Awesome, thanks!

**Pull request merged**
